# Generated by Django 4.2.5 on 2023-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=600)),
                ('topic', models.CharField(choices=[('copyrights', 'Copyrights'), ('patents', 'Patents'), ('trademarks', 'Trademarks')], max_length=60)),
                ('number_of_questions', models.IntegerField()),
                ('required_score_to_pass', models.IntegerField(help_text='required score')),
            ],
            options={
                'verbose_name_plural': 'Quizes',
            },
        ),
    ]
