# Generated by Django 4.2.5 on 2023-09-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='solution_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
