# Generated by Django 4.2.5 on 2023-09-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizquestion_solution_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
