# Generated by Django 4.2.5 on 2023-09-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quizquestion_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
